/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameStatus = IDL.Variant({
  'blackTurn' : IDL.Null,
  'stalemate' : IDL.Null,
  'whiteTurn' : IDL.Null,
  'draw' : IDL.Null,
  'check' : IDL.Null,
  'checkmate' : IDL.Null,
});
export const ChessGame = IDL.Record({
  'fen' : IDL.Text,
  'status' : GameStatus,
  'capturedWhite' : IDL.Text,
  'moveHistory' : IDL.Vec(IDL.Text),
  'capturedBlack' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllGames' : IDL.Func([], [IDL.Vec(ChessGame)], ['query']),
  'getGame' : IDL.Func([IDL.Nat], [ChessGame], ['query']),
  'makeMove' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, GameStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'offerDraw' : IDL.Func([IDL.Nat], [], []),
  'resign' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'startNewGame' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameStatus = IDL.Variant({
    'blackTurn' : IDL.Null,
    'stalemate' : IDL.Null,
    'whiteTurn' : IDL.Null,
    'draw' : IDL.Null,
    'check' : IDL.Null,
    'checkmate' : IDL.Null,
  });
  const ChessGame = IDL.Record({
    'fen' : IDL.Text,
    'status' : GameStatus,
    'capturedWhite' : IDL.Text,
    'moveHistory' : IDL.Vec(IDL.Text),
    'capturedBlack' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllGames' : IDL.Func([], [IDL.Vec(ChessGame)], ['query']),
    'getGame' : IDL.Func([IDL.Nat], [ChessGame], ['query']),
    'makeMove' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, GameStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'offerDraw' : IDL.Func([IDL.Nat], [], []),
    'resign' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'startNewGame' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };