/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChessGame {
    fen: string;
    status: GameStatus;
    capturedWhite: string;
    moveHistory: Array<string>;
    capturedBlack: string;
}
export enum GameStatus {
    blackTurn = "blackTurn",
    stalemate = "stalemate",
    whiteTurn = "whiteTurn",
    draw = "draw",
    check = "check",
    checkmate = "checkmate"
}
export interface backendInterface {
    getAllGames(): Promise<Array<ChessGame>>;
    getGame(id: bigint): Promise<ChessGame>;
    makeMove(gameId: bigint, fen: string, move: string, newStatus: GameStatus, capturedWhite: string, capturedBlack: string): Promise<void>;
    offerDraw(gameId: bigint): Promise<void>;
    resign(gameId: bigint, winner: string): Promise<void>;
    startNewGame(): Promise<bigint>;
}
import type { ChessGame as _ChessGame, GameStatus as _GameStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllGames(): Promise<Array<ChessGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: bigint): Promise<ChessGame> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_ChessGame_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_ChessGame_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async makeMove(arg0: bigint, arg1: string, arg2: string, arg3: GameStatus, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makeMove(arg0, arg1, arg2, to_candid_GameStatus_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeMove(arg0, arg1, arg2, to_candid_GameStatus_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async offerDraw(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.offerDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.offerDraw(arg0);
            return result;
        }
    }
    async resign(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resign(arg0, arg1);
            return result;
        }
    }
    async startNewGame(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewGame();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewGame();
            return result;
        }
    }
}
function from_candid_ChessGame_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChessGame): ChessGame {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fen: string;
    status: _GameStatus;
    capturedWhite: string;
    moveHistory: Array<string>;
    capturedBlack: string;
}): {
    fen: string;
    status: GameStatus;
    capturedWhite: string;
    moveHistory: Array<string>;
    capturedBlack: string;
} {
    return {
        fen: value.fen,
        status: from_candid_GameStatus_n4(_uploadFile, _downloadFile, value.status),
        capturedWhite: value.capturedWhite,
        moveHistory: value.moveHistory,
        capturedBlack: value.capturedBlack
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blackTurn: null;
} | {
    stalemate: null;
} | {
    whiteTurn: null;
} | {
    draw: null;
} | {
    check: null;
} | {
    checkmate: null;
}): GameStatus {
    return "blackTurn" in value ? GameStatus.blackTurn : "stalemate" in value ? GameStatus.stalemate : "whiteTurn" in value ? GameStatus.whiteTurn : "draw" in value ? GameStatus.draw : "check" in value ? GameStatus.check : "checkmate" in value ? GameStatus.checkmate : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChessGame>): Array<ChessGame> {
    return value.map((x)=>from_candid_ChessGame_n2(_uploadFile, _downloadFile, x));
}
function to_candid_GameStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): _GameStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): {
    blackTurn: null;
} | {
    stalemate: null;
} | {
    whiteTurn: null;
} | {
    draw: null;
} | {
    check: null;
} | {
    checkmate: null;
} {
    return value == GameStatus.blackTurn ? {
        blackTurn: null
    } : value == GameStatus.stalemate ? {
        stalemate: null
    } : value == GameStatus.whiteTurn ? {
        whiteTurn: null
    } : value == GameStatus.draw ? {
        draw: null
    } : value == GameStatus.check ? {
        check: null
    } : value == GameStatus.checkmate ? {
        checkmate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
